[workspace]
channels = ["conda-forge", "bioconda"]
name = "CTA_TFM_UOC"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.11.6,<10"
fastqc = ">=0.12.1,<0.13"
fastp = ">=1.0.1,<2"
samtools = ">=1.22.1,<2"
picard = ">=3.4.0,<4"
sambamba = ">=1.0.1,<2"
kallisto = ">=0.51.1,<0.52"
hisat2 = ">=2.2.1,<3"
multiqc = ">=1.32,<2"
