[workspace]
channels = ["conda-forge", "bioconda"]
name = "CTA_TFM_UOC"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.11.6,<10"
fastqc = ">=0.12.1,<0.13"
fastp = ">=1.0.1,<2"
