pipeline: "chip_cr"  # Change to "rnaseq" to change the pipeline

rnaseq:
  raw_fastqs_dir: "data/rnaseq_raw_fastqs"
  qc_dir: "results/rnaseq/qc_raw"
  trimmed_dir: "results/rnaseq/trimmed_fastqs"
  qc_trimmed_dir: "results/rnaseq/qc_trimmed"
  # Kallisto pseudo-alignment
  transcriptome_fasta: "ref/transcriptome.fa.gz"
  kallisto_index: "ref/kallisto.idx"
  kallisto_output_dir: "results/rnaseq/kallisto"
  kallisto:
    extra_args: "--bootstrap-samples=100" # Number of bootstrap samples for kallisto quant
  # HISAT2 alignment
  ref_genome: "ref/genome.fa"
  hisat2_index_dir: "ref/hisat2"
  alignment_dir: "results/rnaseq/aligned_bams"
  hisat2:
    extra_args: ""

wgbs:
  raw_fastqs_dir: "data/wgbs_raw_fastqs" # in this case we are going to obtain the fastqs programatically
  qc_dir: "results/wgbs/qc"
  trimmed_dir: "results/wgbs/trimmed_fastqs"
  qc_trimmed_dir: "results/wgbs/qc_trimmed"
  ref_genome: "ref/genome.fa"
  alignment_dir: "data/wgbs/raw_bams"
  dedup_dir: "data/wgbs/dedup_bams"
  dedup_bam_qc_dir: "results/wgbs/dedup_bam_qc"
  filtered_bam_dir: "data/wgbs/filtered_bams"
  sorted_filtered_bam_dir: "data/wgbs/sorted_filtered_bams"
  filtered_bam_qc_dir: "results/wgbs/filtered_bam_qc"
  mbias_dir: "results/wgbs/mbias"
  methyldackel_dir: "results/wgbs/methyldackel"
  methyldackel_mergecontext_dir: "results/wgbs/methyldackel_mergecontext"
  fastp:
    extra_args: "-q 20 -l 50 --trim_front1 5"
  bismark:
    extra_args: "--non_directional" # Example parameter
  sambamba:
    extra_args: "not unmapped" # Example filter
  methyldackel_mbias:
    extra_args: ""
  methyldackel_extract:
    extra_args: ""

chip_cr:
  raw_fastqs_dir: "data/chip_seq_raw_fastqs"
  qc_dir: "results/chipseq_cutrun/qc_raw"
  ref_genome: "ref/genome.fa"
  trimmed_dir: "results/chipseq_cutrun/trimmed_fastqs"
  qc_trimmed_dir: "results/chipseq_cutrun/qc_trimmed"
  alignment_dir: "results/chipseq_cutrun/aligned_bams"
  bowtie2_index_dir: "ref/bowtie2"
  bam_qc_dir: "results/chipseq_cutrun/bam_qc"
  filtered_bam_dir: "results/chipseq_cutrun/filtered_bams"
  filtered_bam_qc_dir: "results/chipseq_cutrun/filtered_bam_qc"
  deeptools_dir: "results/chipseq_cutrun/deeptools"
  bigwig_dir: "results/chipseq_cutrun/bigwigs"
  subtracted_bigwig_dir: "results/chipseq_cutrun/subtracted_bigwigs"
  fastp:
    extra_args: "-q 20 -l 50"
  bowtie2:
    extra_args: ""
  sambamba:
    markdup_extra_args: ""
    view_extra_args: "not unmapped"
  deeptools:
    multiBamSummary:
      extra_args: "--binSize 10000"
    plotCorrelation:
      extra_args: "--corMethod spearman --skipZeros"
    plotFingerprint:
      extra_args: ""
    bamCoverage:
      normalize_using: "BPM"
      extra_args: "--effectiveGenomeSize 2913022398" # Example for hg38, user should change
    bigwigCompare:
      method: "subtract"
      extra_args: ""