pipeline: "wgbs"  # Change to "rnaseq" to change the pipeline

rnaseq:
  genome_index: "/path/to/rnaseq/index"
  samples: ["S1", "S2"]
  threads: 8

wgbs:
  raw_fastqs_dir: "data/wgbs_raw_fastqs"
  qc_dir: "results/wgbs/qc"
  samples:
    Ctr_1_S1_L003:
      R1: "Ctr_1_S1_L003_R1_001.fastq.gz"
      R2: "Ctr_1_S1_L003_R2_001.fastq.gz"
    Ctr_2_S2_L003:
      R1: "Ctr_2_S2_L003_R1_001.fastq.gz"
      R2: "Ctr_2_S2_L003_R2_001.fastq.gz"
    dazl_1_S5_L003:
      R1: "dazl_1_S5_L003_R1_001.fastq.gz"
      R2: "dazl_1_S5_L003_R2_001.fastq.gz"
    dazl_2_S6_L003:
      R1: "dazl_2_S6_L003_R1_001.fastq.gz"
      R2: "dazl_2_S6_L003_R2_001.fastq.gz"
    ddx4_1_S3_L003:
      R1: "ddx4_1_S3_L003_R1_001.fastq.gz"
      R2: "ddx4_1_S3_L003_R2_001.fastq.gz"
    ddx4_2_S4_L003:
      R1: "ddx4_2_S4_L003_R1_001.fastq.gz"
      R2: "ddx4_2_S4_L003_R2_001.fastq.gz"
    elav2_1_S7_L003:
      R1: "elav2_1_S7_L003_R1_001.fastq.gz"
      R2: "elav2_1_S7_L003_R2_001.fastq.gz"
    elav2_2_S8_L003:
      R1: "elav2_2_S8_L003_R1_001.fastq.gz"
      R2: "elav2_2_S8_L003_R2_001.fastq.gz"
    zar1l_1_S9_L003:
      R1: "zar1l_1_S9_L003_R1_001.fastq.gz"
      R2: "zar1l_1_S9_L003_R2_001.fastq.gz"
    zar1l_2_S10_L003:
      R1: "zar1l_2_S10_L003_R1_001.fastq.gz"
      R2: "zar1l_2_S10_L003_R2_001.fastq.gz"
