pipeline: "wgbs"  # Change to "rnaseq" to change the pipeline

rnaseq:
  genome_index: "/path/to/rnaseq/index"
  samples: ["S1", "S2"]
  threads: 8

wgbs:
  raw_fastqs_dir: "data/wgbs_raw_fastqs" # in this case we are going to obtain the fastqs programatically
  qc_dir: "results/wgbs/qc"
  trimmed_dir: "results/wgbs/trimmed_fastqs"
  qc_trimmed_dir: "results/wgbs/qc_trimmed"
  ref_genome: "ref/genome.fa"
  alignment_dir: "data/wgbs/raw_bams"
  dedup_dir: "data/wgbs/dedup_bams"
  dedup_bam_qc_dir: "results/wgbs/dedup_bam_qc"
  filtered_bam_dir: "data/wgbs/filtered_bams"
  sorted_filtered_bam_dir: "data/wgbs/sorted_filtered_bams"
  filtered_bam_qc_dir: "results/wgbs/filtered_bam_qc"
  mbias_dir: "results/wgbs/mbias"
  methyldackel_dir: "results/wgbs/methyldackel"
  methyldackel_mergecontext_dir: "results/wgbs/methyldackel_mergecontext"
  fastp:
    extra_args: "-q 20 -l 50 --trim_front1 5"
  bismark:
    extra_args: "--non_directional" # Example parameter
  sambamba:
    extra_args: "not unmapped" # Example filter
  methyldackel_mbias:
    extra_args: ""
  methyldackel_extract:
    extra_args: ""
