pipeline: "wgbs"

# Directory where raw fastqs are located
raw_fastqs_dir: "data/wgbs_raw_fastqs/"

# Dictionary that contain all the samples
samples:
  Ctr_1:
    R1: "Ctr_1_S1_L003_R1_001.fastq.gz"
    R2: "Ctr_1_S1_L003_R2_001.fastq.gz"
  Ctr_2:
    R1: "Ctr_2_S2_L003_R1_001.fastq.gz"
    R2: "Ctr_2_S2_L003_R2_001.fastq.gz"
  dazl_1:
    R1: "dazl_1_S5_L003_R1_001.fastq.gz"
    R2: "dazl_1_S5_L003_R2_001.fastq.gz"
  dazl_2:
    R1: "dazl_2_S6_L003_R1_001.fastq.gz"
    R2: "dazl_2_S6_L003_R2_001.fastq.gz"
  ddx4_1:
    R1: "ddx4_1_S3_L003_R1_001.fastq.gz"
    R2: "ddx4_1_S3_L003_R2_001.fastq.gz"
  ddx4_2:
    R1: "ddx4_2_S4_L003_R1_001.fastq.gz"
    R2: "ddx4_2_S4_L003_R2_001.fastq.gz"
  elav2_1:
    R1: "elav2_1_S7_L003_R1_001.fastq.gz"
    R2: "elav2_1_S7_L003_R2_001.fastq.gz"
  elav2_2:
    R1: "elav2_2_S8_L003_R1_001.fastq.gz"
    R2: "elav2_2_S8_L003_R2_001.fastq.gz"
  zar1l_1:
    R1: "zar1l_1_S9_L003_R1_001.fastq.gz"
    R2: "zar1l_1_S9_L003_R2_001.fastq.gz"
  zar1l_2:
    R1: "zar1l_2_S10_L003_R1_001.fastq.gz"
    R2: "zar1l_2_S10_L003_R2_001.fastq.gz"

